// <auto-generated />
using LotteryGenius.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LotteryGenius.API.Migrations
{
    [DbContext(typeof(LotteryGeniusContext))]
    [Migration("20180223165543_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LotteryGenius.API.Data.Entities.Megamillion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ball1")
                        .HasMaxLength(2);

                    b.Property<string>("ball2")
                        .HasMaxLength(2);

                    b.Property<string>("ball3")
                        .HasMaxLength(2);

                    b.Property<string>("ball4")
                        .HasMaxLength(2);

                    b.Property<string>("ball5")
                        .HasMaxLength(2);

                    b.Property<DateTime>("created_on");

                    b.Property<DateTime>("draw_date");

                    b.Property<string>("jackpot");

                    b.Property<string>("megaball")
                        .HasMaxLength(2);

                    b.Property<string>("megaplier")
                        .HasMaxLength(2);

                    b.Property<DateTime>("modified_on");

                    b.HasKey("id");

                    b.ToTable("Megamillions");
                });

            modelBuilder.Entity("LotteryGenius.API.Data.Entities.Powerball", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ball1")
                        .HasMaxLength(2);

                    b.Property<string>("ball2")
                        .HasMaxLength(2);

                    b.Property<string>("ball3")
                        .HasMaxLength(2);

                    b.Property<string>("ball4")
                        .HasMaxLength(2);

                    b.Property<string>("ball5")
                        .HasMaxLength(2);

                    b.Property<DateTime?>("created_on");

                    b.Property<DateTime?>("draw_date");

                    b.Property<string>("jackpot");

                    b.Property<DateTime?>("modified_on");

                    b.Property<string>("powerball")
                        .HasMaxLength(2);

                    b.Property<string>("powerplay")
                        .HasMaxLength(2);

                    b.HasKey("id");

                    b.ToTable("Powerballs");
                });
#pragma warning restore 612, 618
        }
    }
}
